#ifndef CONFIGURATION_H
#define CONFIGURATION_H
#define CONFIGURATION_H_VERSION 02010300

#include "boards.h"
#include "macros.h"

#define STRING_CONFIG_H_AUTHOR "(crathenkali, FlashForge Creator Pro 2)"
#define MACHINE_NAME "OctoFlash Creator MAX"

#define SERIAL_PORT -1
#define SERIAL_PORT_2 3

#define BAUDRATE 250000

#define MOTHERBOARD BOARD_BTT_OCTOPUS_MAX_EZ

#define EXTRUDERS 2
#define DEFAULT_NOMINAL_FILAMENT_DIA 1.75

#define X_DRIVER_TYPE TMC2209
#define Y_DRIVER_TYPE TMC2209
#define Z_DRIVER_TYPE TMC2209
#define E0_DRIVER_TYPE TMC2209
#define E1_DRIVER_TYPE TMC2209

#define X_BED_SIZE 200
#define Y_BED_SIZE 148
#define Z_MAX_POS 150

#define X_MIN_POS 0
#define Y_MIN_POS 0
#define Z_MIN_POS 200

#define DEFAULT_AXIS_STEPS_PER_UNIT {80, 80, 400, 400, 400}
#define DEFAULT_MAX_FEEDRATE {300, 300, 5, 25, 25}
#define DEFAULT_MAX_ACCELERATION {3000, 3000, 100, 10000, 10000}

#define DEFAULT_ACCELERATION 1000
#define DEFAULT_RETRACT_ACCELERATION 1000
#define DEFAULT_TRAVEL_ACCELERATION 1000

#define CLASSIC_JERK
#define JUNCTION_DEVIATION_MM 0.013
#define JUNCTION_DEVIATION_TOLERANCE 0.03

#define S_CURVE_ACCELERATION

#define INVERT_X_DIR true
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true
#define INVERT_E0_DIR false
#define INVERT_E1_DIR false

#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

#define SENSORLESS_HOMING
#define TMC_HOME_SENSITIVITY 8

#define NOZZLE_TO_PROBE_OFFSET {0, 0, 0}

#define FILAMENT_RUNOUT_SENSOR
#define FIL_RUNOUT_ENABLED_DEFAULT true
#define NUM_RUNOUT_SENSORS 2
#define FIL_RUNOUT_STATE LOW
#define FIL_RUNOUT_PULLUP

#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 1
#define TEMP_SENSOR_BED 1

#define HEATER_0_MAXTEMP 275
#define HEATER_1_MAXTEMP 275
#define BED_MAXTEMP 150

#define HOTEND_OFFSET_X {0.0, 25.0}
#define HOTEND_OFFSET_Y {0.0, 0.0}
#define HOTEND_OFFSET_Z {0.0, 0.0}

#define PIDTEMP
#define BANG_MAX 255
#define PID_MAX BANG_MAX
#define PID_K1 0.1

#define PID_PARAMS_PER_HOTEND
#if ENABLED(PIDTEMP)
  #define DEFAULT_Kp_LIST {40.0, 40.0}
  #define DEFAULT_Ki_LIST {2.20, 2.20}
  #define DEFAULT_Kd_LIST {360.0, 360.0}
#endif

#define PIDTEMPBED
#define DEFAULT_bedKp 10.00
#define DEFAULT_bedKi 1.0
#define DEFAULT_bedKd 305.4

#define PREVENT_COLD_EXTRUSION
#define EXTRUDE_MINTEMP 170

#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MAXLENGTH 2000

#define THERMAL_PROTECTION_HOTENDS
#define THERMAL_PROTECTION_BED

#define ENDSTOPPULLUPS
#define ENDSTOP_INVERTING false

#define X_ENDSTOP_INVERTING false
#define Y_ENDSTOP_INVERTING false
#define Z_ENDSTOP_INVERTING false
#define E0_ENDSTOP_INVERTING false
#define E1_ENDSTOP_INVERTING false

#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG

#define SDSUPPORT
#define SDCARD_CONNECTION ONBOARD

#define EVENT_GCODE_SD_ABORT "G28 XY"

#define NOZZLE_PARK_FEATURE
#define NOZZLE_PARK_POINT {10, 10, 20}
#define NOZZLE_PARK_Z_RAISE_MIN 2
#define NOZZLE_PARK_XY_FEEDRATE 100
#define NOZZLE_PARK_Z_FEEDRATE 5

#define AUTO_REPORT_TEMPERATURES
#define AUTO_REPORT_POSITION

#define SHOW_PROGRESS_PERCENT
#define LCD_PROGRESS_BAR
#define PROGRESS_BAR_BAR_TIME 2000
#define PROGRESS_BAR_MSG_TIME 3000
#define PROGRESS_MSG_EXPIRE 0

#define DWIN_CREALITY_LCD
#define DWIN_LCD_PROUI
#define LCD_SERIAL_PORT 2

#define USB_FLASH_DRIVE_SUPPORT
#define USE_UHS3_USB

#define EEPROM_SETTINGS
#define EEPROM_CHITCHAT
#define EEPROM_BOOT_SILENT

#define HOST_ACTION_COMMANDS
#define HOST_PROMPT_SUPPORT
#define HOST_STATUS_NOTIFICATIONS

#endif // CONFIGURATION_H

