#ifndef CONFIGURATION_ADV_H
#define CONFIGURATION_ADV_H
#define CONFIGURATION_ADV_H_VERSION 02010300

#define AXIS_RELATIVE_MODES {false, false, false, false}

#define MICROSTEP_MODES {16, 16, 16, 16, 16}
#define MICROSTEP1 MICROSTEP16

#define TMC2209
#define X_CURRENT 800
#define X_CURRENT_HOME X_CURRENT
#define Y_CURRENT 800
#define Y_CURRENT_HOME Y_CURRENT
#define Z_CURRENT 800
#define Z_CURRENT_HOME Z_CURRENT
#define E0_CURRENT 800
#define E1_CURRENT 800

#define SENSORLESS_HOMING_SENSITIVITY 8
#define X_STALL_SENSITIVITY SENSORLESS_HOMING_SENSITIVITY
#define Y_STALL_SENSITIVITY SENSORLESS_HOMING_SENSITIVITY
#define Z_STALL_SENSITIVITY SENSORLESS_HOMING_SENSITIVITY

#define HYBRID_THRESHOLD
#define X_HYBRID_THRESHOLD 100
#define Y_HYBRID_THRESHOLD 100
#define Z_HYBRID_THRESHOLD 3
#define E0_HYBRID_THRESHOLD 30
#define E1_HYBRID_THRESHOLD 30

#define TMC_ADV() do{ \
  if (X_DRIVER_TYPE == TMC2209) { TMC_ADV_X(TMC2209); } \
  if (Y_DRIVER_TYPE == TMC2209) { TMC_ADV_Y(TMC2209); } \
  if (Z_DRIVER_TYPE == TMC2209) { TMC_ADV_Z(TMC2209); } \
  if (E0_DRIVER_TYPE == TMC2209) { TMC_ADV_E(TMC2209, 0); } \
  if (E1_DRIVER_TYPE == TMC2209) { TMC_ADV_E(TMC2209, 1); } \
} while(0)

#define STEALTHCHOP_XY
#define STEALTHCHOP_Z
#define STEALTHCHOP_E

#define CHOPPER_TIMING CHOPPER_DEFAULT_24V

#define MONITOR_DRIVER_STATUS
#define TMC_DEBUG

#define BABYSTEPPING
#define BABYSTEP_XY
#define BABYSTEP_ZPROBE_OFFSET
#define BABYSTEP_MILLIMETERS
#define BABYSTEP_MINIMUM 0.01
#define BABYSTEP_TICKS 1000

#define DOUBLECLICK_FOR_Z_BABYSTEPPING
#define DOUBLECLICK_MAX_INTERVAL 1250

#define MOVE_Z_WHEN_IDLE
#define MOVE_Z_IDLE_HEIGHT 10

#define FILAMENT_CHANGE_FEATURE
#define FILAMENT_CHANGE_UNLOAD_FEEDRATE 10
#define FILAMENT_CHANGE_UNLOAD_LENGTH 100
#define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE 6
#define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE 6
#define FILAMENT_CHANGE_FAST_LOAD_LENGTH 0
#define ADVANCED_PAUSE_CONTINUOUS_PURGE
#define PAUSE_PARK_NOZZLE_TIMEOUT 3
#define FILAMENT_UNLOAD_PURGE_LENGTH 8
#define PAUSE_PARK_NO_STEPPER_TIMEOUT
#define ADVANCED_PAUSE_PURGE_FEEDRATE 3
#define ADVANCED_PAUSE_PURGE_LENGTH 0

#define PARK_HEAD_ON_PAUSE
#define HOME_BEFORE_FILAMENT_CHANGE

#define FILAMENT_LOAD_UNLOAD_GCODES
#define FILAMENT_UNLOAD_ALL_EXTRUDERS

#define CONFIG_EXAMPLES_DIR "FlashForge/CreatorPro2"

#define ESP3D_WIFI_FEATURE
#define ESP3D_WIFI_PORT 3
#define ESP3D_WIFI_BAUDRATE 115200

#define ADVANCED_OK
#define EXTENDED_CAPABILITIES_REPORT
#define M115_GEOMETRY_REPORT

#define GCODE_MOTION_MODES

#define FAN_SOFT_PWM
#define FAN_SOFT_PWM_REQUIRED
#define FAN_MIN_PWM 50
#define FAN_MAX_PWM 128

#define SDCARD_READONLY
#define SDCARD_EEPROM_EMULATION

#define SD_MENU_CONFIRM_START
#define SD_FILE_SORT

#define STATUS_MESSAGE_SCROLLING
#define LCD_SET_PROGRESS_MANUALLY

#define LCD_SHOW_E_TOTAL
#define SHOW_REMAINING_TIME
#define SHOW_ELAPSED_TIME

#define PRINTCOUNTER

#define USB_FLASH_DRIVE_SUPPORT
#define SDCARD_CONNECTION ONBOARD
#define USE_UHS3_USB

#define LONG_FILENAME_HOST_SUPPORT
#define SCROLL_LONG_FILENAMES

#define POWER_LOSS_RECOVERY
#define POWER_LOSS_PIN 0
#define POWER_LOSS_STATE HIGH

#define CONTROLLER_FAN_EDITABLE
#define CONTROLLERFAN_SPEED_ACTIVE 127
#define CONTROLLERFAN_SPEED_IDLE 0
#define CONTROLLERFAN_IDLE_TIME 30

#define I2C_EEPROM
#define E2END 0x7FFF

#define SDCARD_SORT_ALPHA
#define SDSORT_LIMIT 40
#define FOLDER_SORTING -1
#define SDSORT_GCODE
#define SDSORT_USES_RAM true
#define SDSORT_USES_STACK false
#define SDSORT_CACHE_NAMES true
#define SDSORT_DYNAMIC_RAM false

#define BED_TRAMMING
#define BED_TRAMMING_INCLUDE_CENTER
#define BED_TRAMMING_HEIGHT 0.0
#define BED_TRAMMING_Z_HOP 4.0

#define RESTORE_LEVELING_AFTER_G28
#define GRID_MAX_POINTS_X 5
#define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X

#define MESH_EDIT_GFX_OVERLAY
#define MESH_INSET 10
#define GRID_MAX_POINTS_X 5
#define GRID_MAX_POINTS_Y 5

#define LCD_BED_TRAMMING
#define LCD_BED_LEVELING

#define Z_SAFE_HOMING
#define Z_SAFE_HOMING_X_POINT (X_BED_SIZE / 2)
#define Z_SAFE_HOMING_Y_POINT (Y_BED_SIZE / 2)

#define PROBE_OFFSET_WIZARD
#define PROBE_OFFSET_WIZARD_X (X_BED_SIZE / 2)
#define PROBE_OFFSET_WIZARD_Y (Y_BED_SIZE / 2)
#define PROBE_OFFSET_WIZARD_Z 0

#define AUTO_BED_LEVELING_UBL
#define UBL_HILBERT_CURVE
#define UBL_MESH_WIZARD

#define HOMING_BUMP_MM {5, 5, 2}
#define HOMING_BUMP_DIVISOR {2, 2, 4}

#define QUICK_HOME
#define HOME_Y_BEFORE_X

#define BLTOUCH
#define BLTOUCH_DELAY 500
#define BLTOUCH_FORCE_SW_MODE

#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define Z_MIN_PROBE_PIN PC_2

#endif // CONFIGURATION_ADV_H
